###############################################
##### Okta API related configuration #####
###############################################

#Okta org e.g. example.okta.com or example.oktapreview.com
org=susheel-oie.oktapreview.com
apiToken=********************
rateLimitThreshold=20
activateUsers=true
saltOrder=POSTFIX

###############################################
##### CSV file and user schema related #####
###############################################
csvHeaderRow=firstName,lastName,email,login,value
csvLoginField=login
csvPasswordField=value
csvHeader.login=login
csvHeader.email=email
csvHeader.firstName=firstName
csvHeader.lastName=lastName

###############################################
##### Okta User specific Groups (used by csvGroupField) #####
###############################################
groupIDs=

###############################################
##### Concurrency related #####
###############################################
#Number of threads which will load users in parallel. With default rate limit of 600/min
#for the Users endpoint, 5-7 threads is recommended. This can be adjusted as the rate
#limit itself is changed on the org
numConsumers=1
#How many user records from the CSV to keep in the buffer as the parallel threads take
#this data and move forward with their work
bufferSize=10000
